coverage:
  precision: 2
  round: down
  range: "1...100"
  status:
    patch:
      default:
        target: auto
        threshold: 5%
    project:
      default:
        target: auto
        threshold: 3%
codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
    after_n_builds: 1
ignore:
  # Ignore tests that rely on secrets which are 
  # not passed to incoming PRs to avoid false 
  # alarm on reduced coverage
  - "primo/utils/tests/test_secrets.py"